### PR TITLE
batch of changes

### PR DESCRIPTION
**Pull request by darobin**
These are not huge changes, I seek to:
* Go a little broader than pure interop (which could be limiting for some of the issues we have). Neutrality of infrastructure is key IMHO (eg. choice dialogs), and disintermediation is a goal. We can say that _WINDR Is Coming_.
* I would like the summaries to optionally include solution outlines. Not to prescribe whatever a group could do, but to inform the imagination. I see a big part of this as making sure that regulators understand what alternatives exist or could exist.
* I think we need to look at:
  * Defaults (browser, search) and how to break that stranglehold (can't just be interop here)
  * Recommendation systems (they could be made pluggable, under user control, etc.)
  * Personal data rights protocols (less important, I could skip this one, but things like data portability could use interop principles)
* I want to make sure we stick to principled approaches

### CODE REVIEW

**Comment by mnot** [comment]
Hey,

Can you give examples of requirements for neutrality and disintermediation as applied to specifications? Everything I've seen in this space is characterised as 'interoperability'. 

Also, see rewrite (sorry, will need to rebase).

**Comment by mnot** [comment]
I incorporated some. Regarding:

~~~ html
       <li>Default browser and search choices</li>
       <li>Recommendation systems</li>
       <li>Personal data rights protocols</li>
~~~

I'm a little concerned about making the scope too big; PDR protocols and formats are potentially HUGE, and default choices seems like it's not in keeping with the other areas of focus. Recommendation systems, maybe?

**Comment by darobin** [comment]
I can live without DRP protocols, I only thought about including them because legislative proposals like ACCESS mention variations on verifiable agents and on data portability; and those are usually used in conjunction with DRP. But Consumer Reports are building a DRP, so that could happen there.

The defaults I think we need, because there's no hope for interop to have any effect unless we can break these ties effectively, and because there's solid evidence that legislators need good solutions for choice dialogs and have failed at it spectacularly. The EU's search choice dialog is… wow, so much bad. They asked Google to design the system. It's [an unmitigated disaster](https://twitter.com/NathanLazarus3/status/1361455656176295937?s=20). We know how to fix this, and we have to fix it if interop is going to be more than just a vacuous idea.

Recommendation systems: that's a joint at which to cut for interop. If you could use YT for its video hosting but plug in your own recommendation system (and same for many others), it would make the Web a much better place. Same for, well, all the other things too.

Neutrality: this is simply the idea that infrastructure shouldn't be smart. We don't have to mention it but it's an important value and one that I would expect to guide reforming work. Putting the user in charge of defaults and recommendations is a strong step forward there too.

Disintermediation: if we have interop but no change in defaults, we're not going to see much of it; which is why things like default-picking are important.

**Comment by mnot** [comment]
I've added recommendation systems and highlighted user agency quite a bit more. 

not sure about search/browser defaults -- the problems there seem economic. I'm very conscious of over-extending this group to talk about non-technical things, which risks its authority. Maybe add it later?

**Comment by darobin** [comment]
I'm not sure what you mean by economic? I see these defaults as technical, urgent, and squarely within the remit of the W3C's mission. They need to cover:
* Why switching from defaults to choice dialogs is key to a thriving Web.
* Why it's inappropriate as per TAG principles for a browser to sell the default search.
* How to implement a choice dialog for both of these topics.
* What nutrition labels should be used in offering this choice so that people can make informed decisions about browsers and search.
* What tech infrastructure is required for browsers to be financed if they no longer sell defaults.

**Comment by darobin** [comment]
Other than the lack of defaults/choice dialogs the rest of the text looks good!

**Comment by mnot** [comment]
Done.

**Comment by darobin** [comment]
Thank you! I think it's good to go, closing this.

**Pull request closed without merging**
